= Webdoctor
:page-layout: page
:page-title: "О проекте Webdoctor"
:page-tagline: ""
:page-tags: []
:page-liquid:
:experimental:
:source-highlighter: rouge
:url-asciidoctor: http://asciidoctor.org

{% include JB/setup %}

== О проекте "Webdoctor"

В рамках проекта Webdoctor я занимаюсь "оживлением" заброшенных веб-сайтов.

Ситуация довольно типичная - многие "ура"-специалисты готовы склепать сайт, но поддерживать и тянуть его - это тяжело и плохо оплачивается. Веб-студии также готовы вам помочь - обычно сделав новый сайт, дальнейшая поддержка которого влетит "в копеечку", поскольку размещен он на их хостинге и сделан с помощью их "особых" технологий.

Я предлагаю простое решение:

. На первом этапе я оживляю ваш веб-сайт, решая насущные вопросы. 
. На втором этапе я передаю проект вам в полное управление.

Если насущные вопросы не удается решить за осмысленное время, я формирую набор конкретных рекомендаций относительно дальнейших действий.

Полная передача проекта заключается в полной передаче вам прав на управление доменными именами, хостингом DNS, хостингом сайта и др. ресурсами, а также в обучении вас (или вашего человека) основам управления контентом на сайте, по необходимости - основам веб-технологий. 

Таким образом, на выходе вы получаете фунционирующий веб-сайт и возможность его поддерживать самостоятельно - без завязки на любых третьх лиц - меня, "ура"-специалиста или веб-студию.

Если у вас есть заброшенный веб-сайт и вы хотите его оживить - пишите мне в Telegram +79275308750 или на электронную почту roman.yagodin@gmail.com. Мы договоримся о первичной консультации. Обычно она занимает около часа, стоимость фиксированная - 1000 рублей.
